In [1]:
import pandas as pd

base = pd.read_csv('dataset.csv')

In [2]:
import numpy as np

previsores = base.iloc[:1400000,0:20].values
previsores = np.reshape(previsores, (2000, 700, 20))
print(previsores.shape)

classesQ8 = base.iloc[:1400000, 20:28].values
classesQ8 = np.reshape(classesQ8, (2000, 700, 8))
print(classesQ8.shape)

classesQ3 = base.iloc[:1400000, 28:31].values
classesQ3 = np.reshape(classesQ3, (2000, 700, 3))
print(classesQ3.shape)

(2000, 700, 20)
(2000, 700, 8)
(2000, 700, 3)


In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, CuDNNGRU, Bidirectional

In [5]:
def criarRede(saida):
    model = Sequential()
  
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True), input_shape = (700, 20)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
    
    model.add(Bidirectional(CuDNNGRU(100, return_sequences = True)))
    model.add(Dropout(0.3))
  
    model.add(Dense(saida, activation = 'softmax'))
  
    model.compile(optimizer = 'adam', metrics = ['acc'], loss='categorical_crossentropy')
  
    return model

In [6]:
from sklearn.metrics import balanced_accuracy_score, classification_report, precision_score, recall_score, f1_score, confusion_matrix

def train_and_evaluate_model(model, x_train, y_train, x_test, y_test, saida):
    model.fit(x_train, y_train, epochs = 100, verbose = 1)
  
    predicted = model.predict(x_test)
    y_teste = []
    predict = []
  
    predicted = np.reshape(predicted, (predicted.shape[0] * predicted.shape[1], saida))
    y_test = np.reshape(y_test, (y_test.shape[0] * y_test.shape[1], saida))
    x_test = np.reshape(x_test, (x_test.shape[0] * x_test.shape[1], 20))

    for i in range(len(x_test)):
        cont = 0
        for j in range(len(x_test[i])):
            cont += x_test[i][j]
        if cont != 0:
            y_teste.append(y_test[i])
            predict.append(predicted[i])
    
    y_teste = np.asarray(y_teste)
    predict = np.asarray(predict)

    predicted = predict
    y_test = y_teste
    
    predicted = np.argmax(predicted, axis=1)
    y_test = np.argmax(y_test, axis=1)

    accu.append(balanced_accuracy_score(y_test, predicted)) 
    precisions.append(precision_score(y_test, predicted, average = 'weighted'))
    recalls.append(recall_score(y_test, predicted, average = 'weighted'))
    f1.append(f1_score(y_test, predicted, average = 'weighted'))
    
    print(classification_report(y_test, predicted))
    print('Acurácia')
    print(balanced_accuracy_score(y_test, predicted))
    print('Precisao')
    print(precision_score(y_test, predicted, average = 'weighted'))
    print('Recall')
    print(recall_score(y_test, predicted, average = 'weighted'))
    print('F1')
    print(f1_score(y_test, predicted, average = 'weighted'))
    print(confusion_matrix(y_test, predicted))

In [7]:
from sklearn.model_selection import KFold

kf = KFold(n_splits = 5, shuffle = True)

accu = []
precisions = []
recalls = []
f1 = []

for train_index, test_index in kf.split(previsores):
    model = None
    model = criarRede(8)
    print("TRAIN:", train_index, "TEST:", test_index)
    train_and_evaluate_model(model, previsores[train_index], classesQ8[train_index],
                           previsores[test_index], classesQ8[test_index], 8)

model.summary()

print('Acurácias total')
print(accu)
accu = np.array(accu)
print(accu.mean())
print('Precision total')
print(precisions)
precisions = np.array(precisions)
print(precisions.mean())
print('Recalls total')
print(recalls)
recalls = np.array(recalls)
print(recalls.mean())
print('F1 total')
print(f1)
f1 = np.array(f1)
print(f1.mean())

accu = []
precisions = []
recalls = []
f1 = []

for train_index, test_index in kf.split(previsores):
    model = None
    model = criarRede(3)
    print("TRAIN:", train_index, "TEST:", test_index)
    train_and_evaluate_model(model, previsores[train_index], classesQ3[train_index],
                           previsores[test_index], classesQ3[test_index], 3)
    
model.summary()

print('Acurácias total')
print(accu)
accu = np.array(accu)
print(accu.mean())
print('Precision total')
print(precisions)
precisions = np.array(precisions)
print(precisions.mean())
print('Recalls total')
print(recalls)
recalls = np.array(recalls)
print(recalls.mean())
print('F1 total')
print(f1)
f1 = np.array(f1)
print(f1.mean())

W0823 17:31:55.370047  4388 deprecation.py:506] From c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0823 17:31:55.374036  4388 deprecation.py:506] From c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0823 17:31:55.375055  4388 deprecation.py:506] From c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\init_ops.py

TRAIN: [   0    2    4 ... 1996 1997 1999] TEST: [   1    3    6    8    9   10   11   12   21   22   23   26   29   30
   39   42   44   47   57   59   61   62   66   70   74   76   86   87
   96   97  104  105  106  112  116  121  123  124  138  145  155  165
  175  179  180  182  194  200  204  205  206  208  214  221  223  228
  229  233  235  237  246  249  251  255  260  261  269  272  282  287
  288  295  299  302  304  305  315  325  337  339  347  348  350  357
  369  379  384  392  403  407  408  412  415  419  420  421  427  432
  436  443  446  465  468  475  494  496  497  502  507  513  515  520
  524  527  528  529  534  542  546  549  554  562  567  579  582  585
  594  598  600  603  606  607  617  618  621  624  629  641  643  650
  651  657  662  666  673  674  677  684  690  691  698  702  704  710
  714  717  721  725  727  730  737  738  750  753  762  763  776  784
  785  788  791  795  796  809  810  812  820  828  829  840  841  849
  861  862  865  870  872  8

W0823 17:31:57.565779  4388 deprecation.py:323] From c:\users\gabriel\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/100
1600/1600 [==============================] - 26s 16ms/sample - loss: 0.5907 - acc: 0.1559
Epoch 2/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5306 - acc: 0.1709
Epoch 3/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5240 - acc: 0.1740
Epoch 4/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5161 - acc: 0.1781
Epoch 5/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5135 - acc: 0.1787
Epoch 6/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5092 - acc: 0.1808
Epoch 7/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5050 - acc: 0.1828
Epoch 8/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5022 - acc: 0.1837
Epoch 9/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4967 - acc: 0.1862
Epoch 10/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2946 - acc: 0.2564
Epoch 81/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2931 - acc: 0.2570
Epoch 82/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2924 - acc: 0.2569
Epoch 83/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2923 - acc: 0.2573
Epoch 84/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2898 - acc: 0.2579
Epoch 85/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2894 - acc: 0.2584
Epoch 86/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2882 - acc: 0.2585
Epoch 87/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2856 - acc: 0.2595
Epoch 88/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2843 - acc: 0.2597
Epoch 89/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.28

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4220 - acc: 0.2171
Epoch 29/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4181 - acc: 0.2186
Epoch 30/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4165 - acc: 0.2191
Epoch 31/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4109 - acc: 0.2206
Epoch 32/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4077 - acc: 0.2219
Epoch 33/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4040 - acc: 0.2229
Epoch 34/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4013 - acc: 0.2239
Epoch 35/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3956 - acc: 0.2258
Epoch 36/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3924 - acc: 0.2267
Epoch 37/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.39

[[    4   275    28   155     1   577    57   105]
 [    0 15626   165  1678    17  3165   247   691]
 [    0   387  1319   835     8   867   101   556]
 [    0  1929   474 28044   126  2172   238  1238]
 [    0    54    14   344   221    56     4    46]
 [    1  3668   458  2250    18 11518   873  1779]
 [    0  1415   272  1144    17  3639  1183  1395]
 [    0  1238   497  2329    30  2430   544  4654]]
TRAIN: [   0    1    3 ... 1996 1998 1999] TEST: [   2    5    7   13   37   38   49   50   51   64   72   73   79   81
   88   89  100  108  110  111  120  127  130  139  142  144  151  154
  158  159  166  173  177  199  203  209  213  217  218  222  224  225
  240  250  263  267  275  278  279  283  285  289  292  293  297  298
  300  308  311  312  314  316  317  318  321  329  331  335  338  344
  354  355  361  367  370  371  377  378  380  387  389  396  400  404
  414  417  422  423  430  437  441  453  454  456  458  463  476  482
  492  493  499  501  508  523  543  548  551

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3273 - acc: 0.2444
Epoch 57/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3258 - acc: 0.2449
Epoch 58/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3226 - acc: 0.2462
Epoch 59/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3205 - acc: 0.2467
Epoch 60/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3199 - acc: 0.2470
Epoch 61/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3179 - acc: 0.2478
Epoch 62/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3172 - acc: 0.2480
Epoch 63/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3140 - acc: 0.2487
Epoch 64/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3136 - acc: 0.2491
Epoch 65/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.31

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5258 - acc: 0.1792
Epoch 5/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5184 - acc: 0.1826
Epoch 6/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5143 - acc: 0.1852
Epoch 7/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5101 - acc: 0.1861
Epoch 8/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5054 - acc: 0.1886
Epoch 9/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.5007 - acc: 0.1906
Epoch 10/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4991 - acc: 0.1910
Epoch 11/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4969 - acc: 0.1923
Epoch 12/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4931 - acc: 0.1939
Epoch 13/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4901 - 

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2950 - acc: 0.2616
Epoch 84/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2935 - acc: 0.2623
Epoch 85/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2943 - acc: 0.2619
Epoch 86/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2927 - acc: 0.2623
Epoch 87/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2913 - acc: 0.2631
Epoch 88/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2912 - acc: 0.2631
Epoch 89/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2906 - acc: 0.2630
Epoch 90/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2896 - acc: 0.2634
Epoch 91/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2877 - acc: 0.2640
Epoch 92/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.28

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4041 - acc: 0.2246
Epoch 32/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.4004 - acc: 0.2258
Epoch 33/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3974 - acc: 0.2268
Epoch 34/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3948 - acc: 0.2276
Epoch 35/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3915 - acc: 0.2284
Epoch 36/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3871 - acc: 0.2302
Epoch 37/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3850 - acc: 0.2306
Epoch 38/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3816 - acc: 0.2316
Epoch 39/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3780 - acc: 0.2329
Epoch 40/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.37

TRAIN: [   0    1    2 ... 1996 1997 1999] TEST: [   6   13   26   32   43   44   52   53   60   65   67   77   81   86
   91   92   94  102  105  110  111  118  120  122  125  126  143  149
  160  171  173  177  178  195  196  197  204  205  206  216  219  229
  230  238  241  246  261  262  264  266  279  288  291  295  304  306
  320  329  349  353  354  355  366  372  373  375  383  385  391  400
  413  416  417  419  421  424  425  436  441  445  446  447  458  459
  464  474  476  478  483  486  492  493  499  500  503  505  510  512
  515  516  520  528  535  540  545  551  552  554  558  560  564  567
  573  582  584  585  591  593  595  599  602  606  610  618  629  634
  640  648  651  654  655  656  660  662  671  672  676  681  687  693
  696  699  702  703  710  712  715  717  721  729  733  738  742  751
  755  764  785  790  791  792  804  814  816  819  823  827  842  846
  847  849  853  859  860  872  873  877  881  894  895  897  901  902
  921  927  932  933  936  9

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1692 - acc: 0.9281
Epoch 61/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1673 - acc: 0.9289
Epoch 62/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1653 - acc: 0.9298
Epoch 63/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1646 - acc: 0.9299
Epoch 64/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1622 - acc: 0.9313
Epoch 65/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1611 - acc: 0.9318
Epoch 66/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1597 - acc: 0.9327
Epoch 67/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1577 - acc: 0.9335
Epoch 68/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1560 - acc: 0.9341
Epoch 69/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.15

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2871 - acc: 0.8713
Epoch 15/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2871 - acc: 0.8719
Epoch 16/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2842 - acc: 0.8729
Epoch 17/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2814 - acc: 0.8750
Epoch 18/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2792 - acc: 0.8757
Epoch 19/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2777 - acc: 0.8760
Epoch 20/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2746 - acc: 0.8787
Epoch 21/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2726 - acc: 0.8798
Epoch 22/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2724 - acc: 0.8805
Epoch 23/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.26

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1360 - acc: 0.9432
Epoch 94/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1345 - acc: 0.9437
Epoch 95/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1344 - acc: 0.9438
Epoch 96/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1332 - acc: 0.9443
Epoch 97/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1329 - acc: 0.9446
Epoch 98/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1328 - acc: 0.9443
Epoch 99/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1328 - acc: 0.9445
Epoch 100/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1320 - acc: 0.9447
              precision    recall  f1-score   support

           0       0.70      0.76      0.73     43282
           1       0.71      0.62      0.66     23516
           2       0.78  

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1941 - acc: 0.9174
Epoch 48/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1917 - acc: 0.9187
Epoch 49/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1907 - acc: 0.9191
Epoch 50/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1889 - acc: 0.9200
Epoch 51/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1867 - acc: 0.9208
Epoch 52/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1853 - acc: 0.9213
Epoch 53/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1842 - acc: 0.9218
Epoch 54/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1824 - acc: 0.9229
Epoch 55/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1790 - acc: 0.9243
Epoch 56/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.17

1600/1600 [==============================] - 25s 15ms/sample - loss: 0.3433 - acc: 0.7965
Epoch 2/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3132 - acc: 0.8577
Epoch 3/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3087 - acc: 0.8600
Epoch 4/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3051 - acc: 0.8626
Epoch 5/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3012 - acc: 0.8648
Epoch 6/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2988 - acc: 0.8655
Epoch 7/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2968 - acc: 0.8670
Epoch 8/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.3015 - acc: 0.8637
Epoch 9/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2947 - acc: 0.8672
Epoch 10/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2920 - acc

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1434 - acc: 0.9397
Epoch 81/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1422 - acc: 0.9403
Epoch 82/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1427 - acc: 0.9402
Epoch 83/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1410 - acc: 0.9408
Epoch 84/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1389 - acc: 0.9415
Epoch 85/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1392 - acc: 0.9417
Epoch 86/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1378 - acc: 0.9422
Epoch 87/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1373 - acc: 0.9425
Epoch 88/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1365 - acc: 0.9426
Epoch 89/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.13

1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2189 - acc: 0.9058
Epoch 35/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2144 - acc: 0.9081
Epoch 36/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2111 - acc: 0.9095
Epoch 37/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2098 - acc: 0.9101
Epoch 38/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2068 - acc: 0.9116
Epoch 39/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2045 - acc: 0.9123
Epoch 40/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.2018 - acc: 0.9137
Epoch 41/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1988 - acc: 0.9152
Epoch 42/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.1972 - acc: 0.9159
Epoch 43/100
1600/1600 [==============================] - 22s 14ms/sample - loss: 0.19